### PR TITLE
add check for archive removal, closes #51

### LINKED ISSUE #51: Archives should only be removed from the swarm after all hosting users remove it
Currently the `/v1/dats/remove` route will automatically remove an archive from the swarm. It should double check whether there are other hosting users, first.

### PR DESCRIPTION
**Pull request by joehand**
Don't remove an archive from hypercore-archiver if other users have it hosted.

TODO: 

- [x] Test(s)

Trying to figure out if easier way to test would be to manually add an archive to DB or add another user to the `tests/archives`. We'll probably need another user in the archives tests eventually so will probably do that unless you have a different idea.

### CODE REVIEW

**Comment by pfrazee** [comment]
Nah just add another test user. Also, something I just remembered that's missing is, we need to track dead-archives (https://github.com/joehand/hypercloud/wiki/Archives-Schema). If you can make sure add/remove the dead-archive entries, that'd be good.

**Comment by joehand** [comment]
>  If you can make sure add/remove the dead-archive entries, that'd be good.

I thought that was already happening in the `archiveDb.removeHostedUser` [code here](https://github.com/joehand/hypercloud/blob/master/lib/dbs/archives.js#L121), or did I misunderstand.

**Comment by pfrazee** [comment]
Oh good, ok NM. Forgot I did that.

**Comment by joehand** [comment]
All set here.

**Review by pfrazee — COMMENTED** [review]
Nice work 👍

**Pull request merged**
